import React from "react";
import Svg, { SvgIcon } from "../../../components/Svg/Svg";
import { SvgProps } from "../../../components/Svg/types";

const Icon: React.FC<SvgProps> = (props) => {
  return (
    <SvgIcon
    xmlns="http://www.w3.org/2000/svg"
    width="24px"
    height="24px"
    {...props}>
    <image
      height={24} 
      width={24}
      href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAgAAAAIAAgMAAACJFjxpAAAABGdBTUEAALGPC/xhBQAAACBjSFJN AAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEUAAAA1ucD///+88N2v AAAAAXRSTlMAQObYZgAAAAFiS0dEAmYLfGQAAAAHdElNRQfmAREVIivI75WOAAAEo0lEQVR42u3d UZoaIRCFUX1gCeyHJfAg+99KMpl8aivdVBUU9Iz/fa6GM16jLSaTy4UQQgghpC+lrN0/lnJbuX8o f5MXAsq/rNs/fgOWlRDK/+RFgHLPmv3jA7CkhFCekhcAyibz949bwPQSruUleTKgvGXu/vEdMLWE a6kkTQSUaubtH+uAaSVcy07SJEDZzZz94z5gSgnXcpA0AVAO479/OAa4l3AtjSRnQGt/7xJCG5A9 928W4F2CZH/PEgQFuJYgKsCzBOn+XiUIC3ArQVyAVwlRA3AoQVGASwmqAjxK0BVQhr8tKgsYXoK6 gNElqAsYXIKhgKElmAoYWYKpgIElGAsYV4J9/zElmAsYVEJHAWNK6Nu//22xq4ABJbQKSO1Xib4S 2vu3BY4F3DRTTgVIHgJ7CY2F7z9a4yEwl9Ba9/6TtR4pYwnyowCnQ4PWqk8/V+uxMpXQXDQ/Zlsd WEpo34Uk4/CgArYPq256SAFagLIEwW3gTenVldBeb/v6FgQXDC5g+xNJbpwVJegPwwYfn0lWK92X 7EdSqAkgLEH2QehlsSi6SFaCaCkbQFSCrIDXuwzbVfYCrABBCcKFrIBmCeKFrIBGCfKjgDToQmMB HYDDEsQPZA/goATNWYwdcFBCnAPYLUFRQB9gpwTdYVgPYKcETQGdgOrbYlAt0QeolaA9jewDVEqI cwFvJQTlAr2A1xL0x8G9gJcF4nzApoSgvtz8dlxfQX/1AEDpu3oA4LFEXAO4dQFst+U7SxguHgEo XQDLR7NfBti8Etm+WFsOSF2AzZ/DsACgPaQaDlAe0/1GwNOz0Pjtcifg6VkYlgA0x/UuAMUXFk6A 3NlAN0D8pZUXQPq1nR9A9sWlI+D7WWB+AAYAJF9e+wL6AgAAAAAAAAAAAAAAAADLARcApwHENfv3 fWMyFBDWAPJl8ZPgQgghhBBSjeTuYW8mPUauknUAAAAAYDhAOwOgmli/TvL3ptQz5wSE+oXZY0bz JPCZIYQQQgjZydvNTPabkQEqN3LRApD+DoZoARhnAAAAAADADwFUPlQXC0D64bxYAMYZAAAAAADw UwDpdeRqA6T25vXFJQDTDAAAAAAA+DGA/DoTbIAs2L66uARgmgEAAAAAAD8G8HYGF20A2UFhtAFM MwAAAAAA4JyAUolgRgKQHRQaAaYZAAAAAABwSkD1H+gkwYwEkDwBhhkAAAAAAHBOQKhdmAUzEkD2 BBhmAAAAAADAOQGxdqHkv865CQCSg8JRAMkMAAAAAAA4J6BUo5+JghlXgGQGAAAAAACcErDzO92S duYimfEEiJAAAAAAAOCUgFC/MHvMAAAAAAAAANXE+oUf9AuTlwMIIYQQsja7//nHV9LYmWrKYcbO 1BKOL8wjZ6qJxxfeRs6cE1AaGTkDwA2QGq8CAAAAAHAIIIQQQsiHp3UXMTbv+4e5gPwGiHMBt/MB 5u5feRIA+DhAAgAAwOkAhBBCCPnwzL4b+c5j/7AGkO+AuAZwOw9gzf5PTwIAHwtIAAAAAAAAAAAA AAAAAAAAAICPByw/oABwB8Q1+5/opDSsAeTL4ifBhRBCCCHkK38ApZmT7mFJ1e8AAAAldEVYdGRh dGU6Y3JlYXRlADIwMjItMDEtMTdUMTg6MzQ6NDMrMDM6MDB/Y1P1AAAAJXRFWHRkYXRlOm1vZGlm eQAyMDIyLTAxLTE3VDE4OjM0OjQzKzAzOjAwDj7rSQAAAABJRU5ErkJggg=="/>
  </SvgIcon> )
};


export default Icon;